services:
  db:
    image: postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/findvinyl
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      RAILS_ENV: ${RAILS_ENV}
volumes:
  postgres_volume:
